### ISSUE TITLE
some review

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/ipfs-ds-convert#1]
I read through the code and took some initial review notes. Since there is a lot of code here, i did not go through it as in depth as I would like.

- convert/convert.go line 89, switch should have default case that errors
- saveNewSpec, 'if backup' should probably all get extracted into its own function to make reading things a bit cleaner.
- In general, I'm starting to lean towards oneline single error checks, i.e. `if err := foo(); err != nil {`. It looks a bit cleaner, would love your thoughts on the pattern
- convert/copy.go:248, TODO still relevant?
- config/validate: Should we actually require that paths be strictly within the ipfs repo? I think this is fine to require for now, but likely want to reconsider moving forward

In general, It looks good. Great job @magik6k :) I will give it a try on my own ipfs repo soon.

**Comment by magik6k** [comment]
* 1, 2 done in https://github.com/ipfs/ipfs-ds-convert/commit/fbc9061e1ade99cb8d9497d40f847404d9f6ac98
* err handling: I wanted to be consistent with go-ipfs codebase, I'll see how it looks
* mount check TODO: It is, did a few quick searches on it and it should be simple-ish to do, though will require testing on multiple platforms
* I've chosen to require files to be within the repo as it makes backing-up files easier. When support for other datastores that don't fit that assumption is added (SBS, SQL), they can be ignored for backup or if some form of it can be added (renaming SQL table for example), some interface should be created to avoid having datastore-specific backup logic in places that should focus on more high-level tasks. My idea is to have this logic in https://github.com/ipfs/go-ipfs/pull/3575/files#diff-635108e964d53d70f660d37b18387f16 once it gets extracted to a separate package.

**Comment by magik6k** [comment]
I changed convert.go to use oneline checks.

From https://github.com/ipfs/ipfs-ds-convert/blob/master/convert/convert.go
To https://gist.github.com/magik6k/1f08d29e791b36ff5a247f3c8aff11bf

I don't really think it's a good change since
* Not everything can be wrapped this way consistently as new variables are scoped to the ifs.
* The standard `if err != nil {..` construct is IMO easier to 'automatically' skip when reading the code than reading into the line to see what's called.

Thoughts @whyrusleeping?

**Comment by gammazero** [comment]
@magik6k @whyrusleeping I don't think the mountpoint check is needed, as `os.Rename` should fail if the directory is a mountpoint.  If it is still needed for some reason, then this is how to [test if a directory is mountpoint](https://gist.github.com/gammazero/6de3265ef5e0d1b36d613ca7c8571602).

If the TODO can be removed, then everything else here has been addressed and this can be closed.
