### ISSUE TITLE
add support for ipfs 0.6

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-ds-convert#21]
Currently, the latest version of `ipfs-ds-convert` isn't compatible with ipfs 0.6.0:

```
unsupported fsrepo version: 10
```

@Stebalien I think the release todo should cover a bump for the ds-convert compatibility as well. :)

**Comment by gammazero** [comment]
This has been handled here: https://github.com/ipfs/ipfs-ds-convert/pull/24
Issue can be closed, unless we need to wait for a release to be published.
