### ISSUE TITLE
Provide precompiled binaries for popular platforms

### ISSUE THREAD

**Issue by jay-dee7** [ipfs/ipfs-ds-convert#27]
Right now the only way to install `ipfs-ds-convert` is via `go get`. Since go already has a great support for multiple platforms, it would be great and easy for users to directly wget/curl the pre-compiled binaries instead of first having to install go first and then perform `go get...` for this.

**Comment by aschmahmann** [comment]
There are precompiled binaries available at https://dist.ipfs.io/#ipfs-ds-convert (and via IPFS + DNSLink at https://ipfs.io/ipns/dist.ipfs.io/ipfs-ds-convert).

The binaries are a bit out of date right now, but they'll get updated with the next release of go-ipfs (or sooner depending on timing)
