### ISSUE TITLE
Excessive disk consumption during conversion

### ISSUE THREAD

**Issue by leerspace** [ipfs/ipfs-ds-convert#4]
I'm attempting to convert a couple of my nodes from leveldb over to badger. And in each case I've run out of disk space before the conversion is complete.

While I'd expect the conversion to roughly double the size of the .ipfs directory during conversion, I'm seeing the conversion directory get up to several times bigger than the original datastore before the conversion even completes.

On one node I have roughly 400GB in IPFS and the conversion process filled up the filesystem overnight by consuming almost 2TB. On the other I have roughly 9GB, but I killed that conversion after the conversion directory got up to around 40GB; this node is a laptop with an SSD that isn't very large.

**Comment by magik6k** [comment]
That should definitely not be the case, this might be a problem with badger, I'll look into this.

**Comment by magik6k** [comment]
This is an issue with badger. 

When copying keys we [open new batch each 1024 entries on 16MiB of values](https://github.com/ipfs/ipfs-ds-convert/blob/master/convert/copy.go#L159) to keep memory use at acceptable levels.

Problem is that opening/committing batches with badger seems to generate large disk overhead - here are tests with dataset consisting of ~250k entries 10kb-100kb each:

```
max entries / max size -> on-disk size at 50k entries
1024e / 16M -> 200G

10ke / 1G -> 6.8G

64ke / 1G -> 3.5G
```

Using single batch on-disk size is roughly equal to flatfs, though requires to buffer the whole repo in RAM.

I updated badger to v0.8 tag, though that didn't help.

cc @whyrusleeping @manishrjain

**Comment by manishrjain** [comment]
If the keys are repeated, i.e. the same key is being overwritten multiple times, then you'd want to garbage collect the older values for this key, by calling https://godoc.org/github.com/dgraph-io/badger#DB.RunValueLogGC

In fact, you could call this function, every time you add 1GB of raw data. You don't need to block your writes to do this, just run it in a background serially.

**Comment by magik6k** [comment]
Keys aren't repeated, it's just dumping data from one datastore to the other (from flatfs to badger in this case). The problem is that when putting data in small batches badger seems to allocate way more vlog than what is actually needed

**Comment by manishrjain** [comment]
The batch size makes no difference to value log size. Value log just writes the key-values, and if they are no longer valid, space can be reclaimed later by running value log GC.

**Comment by manishrjain** [comment]
If you could run `badger_info` from the directory where data is stored, and post the output here, that might shed some light into the space usage.

**Comment by leerspace** [comment]
Here is the output I get from `badger_info` after running `ipfs-ds-convert` on a 132 MB flatfs datastore (the only content pinned is Qmb8wsGZNXt5VXZh1pEmYynjB6Euqpq3HYyeAdw2vScTkQ).

Using ipfs-ds-convert to convert this to badger results in an 836 MB badgerds directory.

```
[Manifest]
MANIFEST             28  2017-10-08T09:04:02-05:00
[Level 0]
000001.sst      1122947  2017-10-08T09:04:02-05:00 0
[Value Log]
000000.vlog   874477995  2017-10-08T09:04:01-05:00
[Summary]
Level 0 size: 1122947
Total index size: 1122947
Value log size: 874477995
Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
```

**Comment by manishrjain** [comment]
Badger doesn't do any compression, so maybe that's what's causing your disk usage to be higher than what it is in flatfs.

**Comment by leerspace** [comment]
It *seems* like ipfs-ds-convert is doing something different (and less efficient) than go-ipfs when it comes to using badger. I only have a surface-level understanding of the different pieces involved so my perception might be wrong.

I just did another test using go-ipfs with a fresh repo initialized using the badgerds profile. When I `ipfs pin add -r` the same hash as before, then the badgerds only takes up 115 MB (even less than when I did the test with flatfs before conversion to badger).

FWIW here's the output from `badger_info` from the badger datastore created by go-ipfs.
```
[Manifest]
MANIFEST             52  2017-10-08T17:58:29-05:00
[Level 0]
000001.sst         1498  2017-10-08T17:53:25-05:00 0
000002.sst          664  2017-10-08T17:53:26-05:00 0
000003.sst      1024459  2017-10-08T17:58:29-05:00 0
[Value Log]
000000.vlog   119311173  2017-10-08T17:58:23-05:00
[Summary]
Level 0 size: 1026621
Total index size: 1026621
Value log size: 119311173
Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
```

**Comment by Kubuxu** [comment]
@magik6k could you create minimal test case (small go program/unit test) for it so we eliminate the ipfs-ds-convert from the loop and if it is still a case @manishrjain can reproduce it on his machine?

**Comment by magik6k** [comment]
So this was caused by reusing `Batch` instance, which caused keys to be put multiple times to badger.. @manishrjain sorry for the confusion

**Comment by manishrjain** [comment]
Arr.. You know. Within Dgraph team, this has happened to us one time as well. The new transaction APIs would avoid such a thing.
