### ISSUE TITLE
unsupported fsrepo version: 12

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-ds-convert#44]
I'm running the 13rc1 of ipfs and I got this message as I tried to convert the datastore from flatfs to badgerds:

 ./ipfs-ds-convert convert
convert 2022/05/16 13:24:18 unsupported fsrepo version: 12

**Comment by rjy7wb** [comment]
Is this still an issue, i'm trying to migrate my old datastore to the new badger

**Comment by rjy7wb** [comment]
got around this by downgrading repo version to 11, migrating to badger, the re-upgrading to 12
