### ISSUE TITLE
Proposal: running the conversion tool out-of-the-box without manual configuration

### ISSUE THREAD

**Issue by schomatis** [ipfs/ipfs-ds-convert#7]
I'm trying to understand (with very little knowledge of the datastore specification) why is it necessary to manually update the repository configuration file in order to convert it to the Badger datastore, I would expect to be able to manage the entire operation from the command line, e.g.,

```
ipfs init
ipfs add . -r
ipfs-ds-convert convert <badger options>
```

@magik6k Could you provide me some context to better understand this? And maybe a few pointers that would help me submit a PR to add some command line options that would allow running the conversion tool without adjusting the configuration file (if that is feasible).

**Comment by magik6k** [comment]
You don't really have to edit the config manually, you can do `ipfs config profile apply badger`.

The decision to have this tool not touch the config by default was entirely arbitrary IIRC, so there is nothing stopping you/anyone from implementing some flag on convert that would do that (like `ipfs-ds-convert convert --to badgerds`)

As for the pointers - the config is loaded in https://github.com/ipfs/ipfs-ds-convert/blob/master/convert/prepare.go, which is called from https://github.com/ipfs/ipfs-ds-convert/blob/master/convert/convert.go#L55. You'll probably want to plug this logic after specs are loaded, and also need to save the changed config, preferably before conversion happens.

**Comment by schomatis** [comment]
@magik6k Thanks, with the `profile apply` command is enough for my use case, I just wanted an automatic way to perform the conversion without worrying about the configuration file and I didn't realize the manual modification of the configuration was equivalent to just applying the `badgerds` profile. I'll update the README then.
